// GENERATED by tools/gen-dosbox-config.py -- do not edit by hand.
//
// Upstream produces this with CMake. Boxer builds DOSBox from its own
// Xcode project and never runs CMake, so it is generated and checked in.
// Re-run the generator whenever the DOSBox version changes.

// SPDX-FileCopyrightText:  2020-2025 The DOSBox Staging Team
// SPDX-License-Identifier: GPL-2.0-or-later

#ifndef DOSBOX_DOSBOX_CONFIG_H
#define DOSBOX_DOSBOX_CONFIG_H

// Current DOSBox Staging version without 'v' prefix (e.g., 0.79.1,
// 0.81.1-alpha)
#define DOSBOX_VERSION "0.83.0"

#define DOSBOX_VERSION_SHORT "0.83"

// Minimum 5-char long Git hash of the build; can be longer to guarantee
// uniqueness (e.g., da3c5, c22ef8)
#define BUILD_GIT_HASH "254fba753"


// Operating System
//

// Defined if compiling for OS from BSD family
/* #undef BSD */  // not the target platform

// Defined if compiling for Linux (non-Android)
/* #undef LINUX */  // not the target platform

// Defined if compiling for macOS
#define MACOSX 1

// Defined if compiling for Windows (any option)
#ifndef WIN32
/* #undef WIN32 */  // not the target platform
#endif


// CPU and FPU emulation
//
// These defines are mostly relevant to modules src/cpu/ and src/fpu/

// Target CPU we're compiling for; only one of these can be 1
#if defined(__aarch64__) || defined(__arm64__)
#define C_TARGET_CPU_ARM 1
#else
#define C_TARGET_CPU_ARM 0
#endif
#if defined(__x86_64__) || defined(__i386__)
#define C_TARGET_CPU_X86 1
#else
#define C_TARGET_CPU_X86 0
#endif

// Define to 1 if target CPU supports unaligned memory access
#define C_UNALIGNED_MEMORY 1

// Define to 1 if the target platform needs per-page dynamic core write or execute (W^X) tagging
#define C_PER_PAGE_W_OR_X 1

// Define to 1 to use the x86_64 dynamic CPU core
// Can not be used together with C_DYNREC
#if defined(__x86_64__) || defined(__i386__)
#define C_DYNAMIC_X86 1
#else
#define C_DYNAMIC_X86 0
#endif

// Define to 1 to use the recompiling CPU core
// Can not be used together with C_DYNAMIC_X86
#define C_DYNREC 1

// Define to 1 to use the FPU core implemented in x86 assembler
#if defined(__x86_64__) || defined(__i386__)
#define C_FPU_X86 1
#else
#define C_FPU_X86 0
#endif

// Define to 1 to use inlined memory functions in CPU core
#define C_CORE_INLINE 1


// Emulator features
//
// Turn on or off optional emulator features that depend on external libraries.
// This way it's easier to port or package on a new platform, where these
// libraries might be missing.

// Define to 1 to use opengl display output support
#define C_OPENGL 1

// Define to 1 to enable internal debugger (using ncurses or pdcurses)
#define C_DEBUGGER 0  // no internal debugger (PDCurses is not compiled)

// Define to 1 to enable heavy debugging (requires C_DEBUGGER)
#define C_HEAVY_DEBUGGER 0  // requires C_DEBUGGER

// Define to 1 to enable MT-32 emulator
#define C_MT32EMU 0  // Boxer supplies MT-32 via its own MT32Emu framework; src/midi/mt32.cpp is not compiled

// Define to 1 to enable the FluidSynth MIDI device. It is the only MIDI device
// that needs an external library, so embedders that do not link FluidSynth can
// turn it off; every other device is satisfied from the tree.
#define C_FLUIDSYNTH 0  // Boxer does not link FluidSynth; src/midi/fluidsynth.cpp is not compiled

// Define to 1 to enable the slirp Ethernet backend (NE2000 networking). It is
// the only Ethernet backend and needs libslirp; embedders that do not link it
// build without network support.
#define C_SLIRP 0  // Boxer does not link libslirp and exposes no network settings; src/network/ethernet_slirp.cpp is not compiled

// Define to 1 to enable parallel port printer redirection. This requires a
// host-side printer backend to be linked in (Boxer provides one via
// BXCoalface); the stock CMake build leaves it off.
#define C_PRINTER 1

// Define to 1 when building as Boxer's embedded emulator core. This enables
// the boxer_* hook call sites, which are declared by Boxer's BXCoalface.h and
// must be resolved by the embedding application.
#define C_BOXER 1

// Define to 1 to enable mouse mapping support
#define C_MANYMOUSE 1

// ManyMouse optionally supports the X Input 2.0 protocol (regardless of OS). It
// uses the following define to definitively indicate if it should or shouldn't
// use the X Input 2.0 protocol. If this is left undefined, then ManyMouse makes
// an assumption about availability based on OS type.
#define SUPPORT_XINPUT2 0  // not macOS

// Compiler supports Core Audio headers
#define C_COREAUDIO 1

// Compiler supports Core MIDI headers
#define C_COREMIDI 1

// Compiler supports Core Foundation headers
#define C_COREFOUNDATION 1

// Compiler supports Core Services headers
#define C_CORESERVICES 1

// Define to 1 to enable ALSA MIDI support
#define C_ALSA 0  // not macOS


// Defines for checking availability of standard functions and structs.
//
// Sometimes available functions, structs, or struct fields differ slightly
// between operating systems.

// Define to 1 when zlib-ng support is provided by the system
#define C_SYSTEM_ZLIB_NG 0  // no system zlib-ng

// Defined if synchronous I/O multiplexing is available
#define HAVE_FD_ZERO 1

// Defined if function clock_gettime is available
#define HAVE_CLOCK_GETTIME 1

// Defined if function __builtin_available is available
#define HAVE_BUILTIN_AVAILABLE 1

// Defined if function __builtin___clear_cache is available
#define HAVE_BUILTIN_CLEAR_CACHE 1

// Defined if function mprotect is available
#define HAVE_MPROTECT 1

// Defined if function mmap is available
#define HAVE_MMAP 1

// Defined if mmap flag MAPJIT is available
#define HAVE_MAP_JIT 1

// Defined if function pthread_jit_write_protect_np is available
#define HAVE_PTHREAD_WRITE_PROTECT_NP 1

// Defined if function sys_icache_invalidate is available
#define HAVE_SYS_ICACHE_INVALIDATE 1

// Defined if function pthread_setname_np is available
#define HAVE_PTHREAD_SETNAME_NP 1

// Defind if function setpriority is available
#define HAVE_SETPRIORITY 1

// Defind if function strnlen is available
#define HAVE_STRNLEN 1

// field d_type in struct dirent is not defined in POSIX
// Some OSes do not implement it (e.g. Haiku)
#define HAVE_STRUCT_DIRENT_D_TYPE 1


// Available headers
//
// Checks for non-POSIX headers and POSIX headers not supported on Windows.

#define HAVE_LIBGEN_H 1
#define HAVE_NETINET_IN_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRINGS_H 1
#define HAVE_SYS_SOCKET_H 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_SYS_XATTR_H 1


// Windows-related defines
//

// Prevent <windows.h> from clobbering std::min and std::max
#ifndef NOMINMAX
/* #undef NOMINMAX */  // Windows only
#endif

// Enables mathematical constants (such as M_PI) in Windows math.h header
// https://docs.microsoft.com/en-us/cpp/c-runtime-library/math-constants
/* #undef _USE_MATH_DEFINES */  // Windows only

// Modern MSVC provides POSIX-like routines, so prefer that over built-in
#define HAVE_STRNLEN 1

// Holds the CMAKE_INSTALL_DATADIR specified during project setup. This can
// be used as a fallback if the user hasn't populated their
// XDG_DATA_HOME or XDG_DATA_DIRS.
#define CUSTOM_DATADIR "/usr/local/share"


#endif // DOSBOX_DOSBOX_CONFIG_H
